### ISSUE TITLE
Use bananahackers.net domain directly without web forward

### ISSUE THREAD

**Issue by farooqkz** [ivan-hc/bananahackers#3]
That would be neater. Wouldn't be?

**Comment by ivan-hc** [comment]
the domain name is in the hands of Luxferre, I only supply the pages. Also, the links have already been changed in all videos on the YouTube channel. The main problem was providing these pages to the public without them suddenly being blocked by Google, and I managed to do that by moving everything to GitHub. I've already spent a whole day changing all the links in the videos of the YouTube channel, I certainly don't want to do it anymore, especially now that I don't have time, nor do I have to dedicate myself to KaiOS again in the future (except for the comments I must reply to on Youtube, which is all I have left to do after my militancy in the community). 

So consider this "messy" link as a link with the signature of the site's author ("ivan-hc", ie me), at least for what his stay with the bananahackers community has been and his engagement with KaiOS users, which is only "the past" for me.

**Comment by cyan-2048** [comment]
you do not need to change the ivan-hc links... you can set bananahackers.net as the domain in github pages and still keep the ivan-hc.github.io domain running.... luxferre would probably be fine with setting up github pages, since the webstore is literally a github pages website as well....

**Comment by cyan-2048** [comment]
example: https://jkelol111.github.io/webstore/#dotkvp
